USE reminder_app;

ALTER TABLE reminders ADD COLUMN IF NOT EXISTS category     VARCHAR(50)  DEFAULT 'Personal';
ALTER TABLE reminders ADD COLUMN IF NOT EXISTS priority     INT          DEFAULT 5;
ALTER TABLE reminders ADD COLUMN IF NOT EXISTS lat          DECIMAL(10,7) DEFAULT NULL;
ALTER TABLE reminders ADD COLUMN IF NOT EXISTS lng          DECIMAL(10,7) DEFAULT NULL;
ALTER TABLE reminders ADD COLUMN IF NOT EXISTS location_name VARCHAR(255) DEFAULT NULL;
ALTER TABLE reminders ADD COLUMN IF NOT EXISTS day_of_week VARCHAR(20)  DEFAULT NULL;

CREATE TABLE IF NOT EXISTS digest_logs (
  id         INT AUTO_INCREMENT PRIMARY KEY,
  user_id    INT NOT NULL,
  digest     TEXT NOT NULL,
  sent_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS weather_cache (
  id         INT AUTO_INCREMENT PRIMARY KEY,
  location   VARCHAR(255) NOT NULL,
  forecast   TEXT NOT NULL,
  fetched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX(location)
);
